import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'css/tailwind.css';
import StyledComponentsRegistry from '../lib/AntdRegistry';
import Layout from '@/components/Layout/index';
import { ConfigProvider, theme } from 'antd';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: `c2c's Blog`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Layout>{children}</Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
